#!/usr/bin/env python3
"""Regenerate Chief of Staff favicon assets.

Outputs raster PNGs + an SVG mark, then writes them as base64 into
src/web/icons.js so the Worker can serve them without a build step.

Run from the repo root:
    pip install Pillow
    python3 apps/chief-of-staff/scripts/gen-icons.py

Mark: paper-coloured ✦ "sparkle" on dark ink, rounded square.
"""
from __future__ import annotations

import base64
import os
import sys
from pathlib import Path

from PIL import Image, ImageDraw

INK   = (0x1f, 0x24, 0x33, 255)   # #1f2433 — body text
PAPER = (0xfb, 0xfa, 0xf6, 255)   # #fbfaf6 — page background

HERE   = Path(__file__).resolve().parent
APP    = HERE.parent
WEB    = APP / "src" / "web"
ICONS  = WEB / "icons"


def four_point_star(cx: float, cy: float, R: float, r: float):
    # 8 vertices alternating outer/inner — the ✦ sparkle silhouette.
    return [
        (cx,       cy - R),
        (cx + r,   cy - r),
        (cx + R,   cy    ),
        (cx + r,   cy + r),
        (cx,       cy + R),
        (cx - r,   cy + r),
        (cx - R,   cy    ),
        (cx - r,   cy - r),
    ]


def render(size: int, square: bool = False) -> Image.Image:
    # Render at 4x and downsample for crisp edges at small sizes.
    scale = 4
    S = size * scale
    img = Image.new("RGBA", (S, S), (0, 0, 0, 0))
    d = ImageDraw.Draw(img)
    radius = 0 if square else int(S * 0.20)
    d.rounded_rectangle((0, 0, S - 1, S - 1), radius=radius, fill=INK)
    cx = cy = S // 2
    R = int(S * 0.34)
    r = int(R * 0.18)
    d.polygon(four_point_star(cx, cy, R, r), fill=PAPER)
    return img.resize((size, size), Image.LANCZOS)


SIZES = {
    "favicon-16.png":         (16,  False),
    "favicon-32.png":         (32,  False),
    "favicon-48.png":         (48,  False),
    "apple-touch-icon.png":   (180, False),
    "icon-192.png":           (192, False),
    "icon-512.png":           (512, False),
    "icon-512-maskable.png":  (512, True),
}


def svg_source() -> str:
    R = 0.34
    r = R * 0.18
    pts = [
        (0.5,     0.5 - R),
        (0.5 + r, 0.5 - r),
        (0.5 + R, 0.5    ),
        (0.5 + r, 0.5 + r),
        (0.5,     0.5 + R),
        (0.5 - r, 0.5 + r),
        (0.5 - R, 0.5    ),
        (0.5 - r, 0.5 - r),
    ]
    pts_str = " ".join(f"{x*512:.2f},{y*512:.2f}" for x, y in pts)
    return (
        '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512">\n'
        '  <rect width="512" height="512" rx="102" ry="102" fill="#1f2433"/>\n'
        f'  <polygon points="{pts_str}" fill="#fbfaf6"/>\n'
        '</svg>\n'
    )


def chunk(s: str, n: int = 76) -> str:
    return "\n".join(s[i:i + n] for i in range(0, len(s), n))


def main() -> int:
    ICONS.mkdir(parents=True, exist_ok=True)
    for name, (sz, sq) in SIZES.items():
        render(sz, square=sq).save(ICONS / name, optimize=True)
    render(48).save(ICONS / "favicon.ico", sizes=[(16, 16), (32, 32), (48, 48)])
    (ICONS / "favicon.svg").write_text(svg_source())

    # Emit src/web/icons.js with embedded base64.
    files = [
        ("FAVICON_ICO_B64",       "favicon.ico"),
        ("FAVICON_16_PNG_B64",    "favicon-16.png"),
        ("FAVICON_32_PNG_B64",    "favicon-32.png"),
        ("APPLE_TOUCH_ICON_B64",  "apple-touch-icon.png"),
        ("ICON_192_PNG_B64",      "icon-192.png"),
        ("ICON_512_PNG_B64",      "icon-512.png"),
        ("ICON_512_MASKABLE_B64", "icon-512-maskable.png"),
    ]
    parts = [
        "/**",
        " * web/icons.js — branded favicon assets for Chief of Staff.",
        " *",
        " * Generated by scripts/gen-icons.py — do not edit by hand.",
        " * The Worker serves these from /favicon.ico, /favicon.svg,",
        " * /apple-touch-icon.png, /icon-192.png, /icon-512.png and",
        " * /manifest.webmanifest.",
        " */",
        "",
    ]
    for var, name in files:
        b = (ICONS / name).read_bytes()
        b64 = base64.b64encode(b).decode()
        parts.append(f"export const {var} =")
        parts.append('  "' + chunk(b64).replace("\n", '" +\n  "') + '";')
        parts.append("")

    parts.append("export const FAVICON_SVG = `" + svg_source().rstrip().replace("`", "\\`") + "`;")
    parts.append("")
    parts.append("export const MANIFEST_JSON = JSON.stringify({")
    parts.append('  name: "Chief of Staff",')
    parts.append('  short_name: "Chief of Staff",')
    parts.append('  description: "Personal chief of staff agent.",')
    parts.append('  start_url: "/app",')
    parts.append('  scope: "/app",')
    parts.append('  display: "standalone",')
    parts.append('  background_color: "#fbfaf6",')
    parts.append('  theme_color: "#1f2433",')
    parts.append('  icons: [')
    parts.append('    { src: "/icon-192.png", sizes: "192x192", type: "image/png" },')
    parts.append('    { src: "/icon-512.png", sizes: "512x512", type: "image/png" },')
    parts.append('    { src: "/icon-512-maskable.png", sizes: "512x512", type: "image/png", purpose: "maskable" },')
    parts.append('  ],')
    parts.append("});")
    parts.append("")
    parts.append("export function bytesFromB64(b64) {")
    parts.append("  const bin = atob(b64);")
    parts.append("  const out = new Uint8Array(bin.length);")
    parts.append("  for (let i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i);")
    parts.append("  return out;")
    parts.append("}")
    parts.append("")

    (WEB / "icons.js").write_text("\n".join(parts))
    print(f"wrote {WEB / 'icons.js'} and {len(SIZES) + 2} files in {ICONS}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
